# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in apples-tests.gemspec
gemspec

gem "rake", "~> 13.0"
gem "linkeddata", "~> 3.2.0"
gem "rubocop", "~> 1.21"
gem "rspec", "~> 3.11.0"
gem "rdf-raptor", "~> 3.1.0"
gem "ruby-debug-ide"
gem "xml-simple", "~>1.1.8"
gem "parseconfig", "~>1.1.2"
gem "rest-client", "~>2.1.0"
gem "metainspector", "~> 5-11-2"
